[workspace]
members = [
    "pangraphx-core",
    "pangraphx-cli"
]
resolver = "2"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
# Your strict settings
pedantic = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }