[package]
name = "pangraphx-core"
version = "0.1.0"
edition = "2024"
description = "Core library for PanGraphX: a toolkit for genome graph loading and format conversion."
license = "MIT"
repository = "https://github.com/samuelburger27/PanGraphX"

# Inside crate_a/Cargo.toml and crate_b/Cargo.toml
[lints]
workspace = true

[features]
default = []
odgi = ["dep:odgi-ffi"]

[dependencies]
bio = "3.0.0"
gbwt = "0.3.1"
gfa = "0.10.1"
log = "0.4.28"
odgi-ffi = { version = "1.1.3", optional = true }
prost = "0.13"
rayon = "1.7"
simple-sds-sbwt = "0.3.2"
thiserror = "2.0.17"
tempfile = "3"

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
