[package]
name = "pangraphx-cli"
version = "0.1.0"
edition = "2024"
description = "CLI tool based on PanGraphX: converting and inspecting genome graphs."
license = "MIT"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
simplelog = "0.12"
log = "0.4.28"
pangraphx-core = { path = "../pangraphx-core" }
env_logger = "0.11.8"
textwrap = "0.16.2"
colored = "3.1.1"
